#!/usr/bin/env python3
"""Compile the NAICS folder tree into the published site.

Run from the repository root:

    python build.py

Reads   NAICS/<sector>/<subsector>/<group>/<industry>/<code> - <title>/<code><POLICY>.txt
Writes  docs/data.js          the whole payload, for the lookup tool at /
        docs/naics/**         one crawlable page per code and per policy
        docs/sitemap.xml      every indexable URL
        docs/robots.txt       , docs/404.html, docs/.nojekyll

Every 6-digit code folder becomes a valid, searchable code. Policy files that are
empty are simply omitted from the payload; the tool renders them as NO DATA and
the matching page is generated but marked noindex.
"""

import datetime
import json
import os
import re
import sys

import pages

POLICIES = [
    ("CAU", "Commercial Auto"),
    ("GL", "General Liability"),
    ("PL", "Professional Liability"),
    ("WC", "Workers Compensation"),
    ("CYB", "Cyber Liability"),
    ("BOP", "Business Owner's Policy"),
    ("IM", "Inland Marine"),
    ("UMB", "Umbrella"),
]

ROOT = os.path.dirname(os.path.abspath(__file__))
NAICS_DIR = os.path.join(ROOT, "NAICS")
DOCS_DIR = os.path.join(ROOT, "docs")
OUT_PATH = os.path.join(DOCS_DIR, "data.js")
STATE_PATH = os.path.join(ROOT, ".seo-state.json")

LEAF = re.compile(r"^(\d{6}) - (.+)$")


def collect():
    """Walk the source tree into {code: {title, sector, subsector, policies}}."""
    records = {}
    errors = []
    populated = 0

    for dirpath, dirnames, _ in os.walk(NAICS_DIR):
        match = LEAF.match(os.path.basename(dirpath))
        if not match or dirnames:
            continue

        code, folder_title = match.group(1), match.group(2)
        parts = os.path.relpath(dirpath, NAICS_DIR).split(os.sep)
        record = {
            "title": folder_title,
            "sector": parts[0] if len(parts) > 0 else "",
            "subsector": parts[1] if len(parts) > 1 else "",
            "policies": {},
        }

        for policy_code, _name in POLICIES:
            path = os.path.join(dirpath, code + policy_code + ".txt")
            if not os.path.isfile(path) or os.path.getsize(path) == 0:
                continue
            try:
                with open(path, encoding="utf-8") as handle:
                    record["policies"][policy_code] = json.load(handle)
            except (ValueError, OSError) as exc:
                errors.append("%s: %s" % (path, exc))
                continue
            populated += 1
            # The folder name is truncated at 60 characters; a populated file
            # carries the full official title, so prefer it when present.
            full = record["policies"][policy_code].get("naics_title")
            if full:
                record["title"] = full

        records[code] = record

    return records, populated, errors


def write_data_js(records):
    """The tool at / loads this once. Shape is unchanged from before docs/."""
    titles = {code: record["title"] for code, record in records.items()}
    data = {code: record["policies"] for code, record in records.items()
            if record["policies"]}
    payload = {
        # Third element is the URL segment, so the tool can push real paths.
        "policies": [[abbr, name, pages.POLICY_SLUGS[abbr]] for abbr, name in POLICIES],
        "codes": sorted(titles),
        "titles": titles,
        "data": data,
    }
    os.makedirs(DOCS_DIR, exist_ok=True)
    with open(OUT_PATH, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("/* Generated by build.py. Do not edit by hand. */\n")
        handle.write("window.BOLD_RAVEN=")
        json.dump(payload, handle, separators=(",", ":"), ensure_ascii=False,
                  sort_keys=True)
        handle.write(";\n")
    return len(data)


def main():
    if not os.path.isdir(NAICS_DIR):
        sys.exit("NAICS directory not found at " + NAICS_DIR)

    records, populated, errors = collect()
    if not records:
        sys.exit("No 6-digit code folders found under " + NAICS_DIR)

    with_data = write_data_js(records)

    policies = [(abbr, name, pages.POLICY_SLUGS[abbr]) for abbr, name in POLICIES]
    today = datetime.date.today().isoformat()
    result = pages.build(records, policies, DOCS_DIR, STATE_PATH, today)

    size_kb = os.path.getsize(OUT_PATH) / 1024.0
    print("codes:            %d" % len(records))
    print("populated files:  %d" % populated)
    print("codes with data:  %d" % with_data)
    print("data.js:          %.1f KB" % size_kb)
    print("pages written:    %d  (%d changed, %d removed)"
          % (result["pages"], result["changed"], result["removed"]))
    print("indexable URLs:   %d" % result["indexable"])
    for err in errors:
        print("ERROR " + err)
    if errors:
        sys.exit(1)


if __name__ == "__main__":
    main()
