#!/usr/bin/env python3
"""Compile the NAICS folder tree into data.js for the Bold Raven static site.

Run from the repository root:

    python build.py

Reads   NAICS/<sector>/<subsector>/<group>/<industry>/<code> - <title>/<code><POLICY>.txt
Writes  data.js

Every 6-digit code folder becomes a valid, searchable code. Policy files that are
empty are simply omitted from the output; the site renders them as NO DATA.
"""

import json
import os
import re
import sys

POLICIES = [
    ("CAU", "Commercial Auto"),
    ("GL", "General Liability"),
    ("PL", "Professional Liability"),
    ("WC", "Workers Compensation"),
    ("CYB", "Cyber Liability"),
    ("BOP", "Business Owner's Policy"),
    ("IM", "Inland Marine"),
    ("UMB", "Umbrella"),
]

ROOT = os.path.dirname(os.path.abspath(__file__))
NAICS_DIR = os.path.join(ROOT, "NAICS")
OUT_PATH = os.path.join(ROOT, "data.js")

LEAF = re.compile(r"^(\d{6}) - (.+)$")


def main():
    if not os.path.isdir(NAICS_DIR):
        sys.exit("NAICS directory not found at " + NAICS_DIR)

    titles = {}
    data = {}
    errors = []
    populated = 0

    for dirpath, dirnames, filenames in os.walk(NAICS_DIR):
        match = LEAF.match(os.path.basename(dirpath))
        if not match or dirnames:
            continue

        code, folder_title = match.group(1), match.group(2)
        titles[code] = folder_title
        policies = {}

        for policy_code, _ in POLICIES:
            path = os.path.join(dirpath, code + policy_code + ".txt")
            if not os.path.isfile(path) or os.path.getsize(path) == 0:
                continue
            try:
                with open(path, encoding="utf-8") as handle:
                    policies[policy_code] = json.load(handle)
            except (ValueError, OSError) as exc:
                errors.append("%s: %s" % (path, exc))
                continue
            populated += 1
            # The folder name is truncated at 60 characters; a populated file
            # carries the full official title, so prefer it when present.
            full = policies[policy_code].get("naics_title")
            if full:
                titles[code] = full

        if policies:
            data[code] = policies

    codes = sorted(titles)
    if not codes:
        sys.exit("No 6-digit code folders found under " + NAICS_DIR)

    payload = {
        "policies": [list(p) for p in POLICIES],
        "codes": codes,
        "titles": titles,
        "data": data,
    }

    with open(OUT_PATH, "w", encoding="utf-8") as handle:
        handle.write("/* Generated by build.py. Do not edit by hand. */\n")
        handle.write("window.BOLD_RAVEN=")
        json.dump(payload, handle, separators=(",", ":"), ensure_ascii=False, sort_keys=True)
        handle.write(";\n")

    size_kb = os.path.getsize(OUT_PATH) / 1024.0
    print("codes:            %d" % len(codes))
    print("populated files:  %d" % populated)
    print("codes with data:  %d" % len(data))
    print("data.js:          %.1f KB" % size_kb)
    for err in errors:
        print("ERROR " + err)
    if errors:
        sys.exit(1)


if __name__ == "__main__":
    main()
